---
label: Config
hide_body: true
is_partial: false
fields:
  - type: text
    name: title
    label: Title
    description: Site title
    config:
      required: true
  - type: field_group
    name: footer
    label: Footer Configuration
    fields:
      - type: select
        name: landing_style
        label: Home Footer Style
        description: The style of the home page footer
        config:
          required: true
          source:
            type: custom
          options:
            - alt
            - style1-alt
            - style2-alt
            - style3-alt
            - style4-alt
      - type: select
        name: alt_style
        label: Default Footer Style
        description: The style of the page footer
        config:
          required: true
          source:
            type: custom
          options:
            - alt
            - style1-alt
            - style2-alt
            - style3-alt
            - style4-alt
      - type: text
        name: copyright
        label: Copyright Text
        description: The text displayed in the copyright inside the page footer
  - type: select
    name: palette
    label: Color Palette
    description: The color palette used for the page
    config:
      required: true
      source:
        type: custom
      options:
        - blue
        - green
        - purple
  - type: field_group
    name: palettes
    hidden: true
    fields:
      - type: field_group
        name: blue
        fields:
          - type: field_group
            name: sass
            fields:
              - type: text
                name: bg
              - type: text
                name: accent1
              - type: text
                name: accent2
              - type: text
                name: accent3
      - type: field_group
        name: green
        fields:
          - type: field_group
            name: sass
            fields:
              - type: text
                name: bg
              - type: text
                name: accent1
              - type: text
                name: accent2
              - type: text
                name: accent3
      - type: field_group
        name: purple
        fields:
          - type: field_group
            name: sass
            fields:
              - type: text
                name: bg
              - type: text
                name: accent1
              - type: text
                name: accent2
              - type: text
                name: accent3
